apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: nrnz2y92e-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/nrnz2y92e-java-springboot-gitops